/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package platform;

public class item_inventory_info_vector {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected item_inventory_info_vector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(item_inventory_info_vector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PlatformModuleJNI.delete_item_inventory_info_vector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public item_inventory_info_vector() {
    this(PlatformModuleJNI.new_item_inventory_info_vector__SWIG_0(), true);
  }

  public item_inventory_info_vector(long n) {
    this(PlatformModuleJNI.new_item_inventory_info_vector__SWIG_1(n), true);
  }

  public long size() {
    return PlatformModuleJNI.item_inventory_info_vector_size(swigCPtr, this);
  }

  public long capacity() {
    return PlatformModuleJNI.item_inventory_info_vector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    PlatformModuleJNI.item_inventory_info_vector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return PlatformModuleJNI.item_inventory_info_vector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    PlatformModuleJNI.item_inventory_info_vector_clear(swigCPtr, this);
  }

  public void add(item_inventory_info x) {
    PlatformModuleJNI.item_inventory_info_vector_add(swigCPtr, this, item_inventory_info.getCPtr(x), x);
  }

  public item_inventory_info get(int i) {
    return new item_inventory_info(PlatformModuleJNI.item_inventory_info_vector_get(swigCPtr, this, i), false);
  }

  public void set(int i, item_inventory_info val) {
    PlatformModuleJNI.item_inventory_info_vector_set(swigCPtr, this, i, item_inventory_info.getCPtr(val), val);
  }

}
