/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package platform;

public class item_inventory_info {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected item_inventory_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(item_inventory_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PlatformModuleJNI.delete_item_inventory_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setItem_name(String value) {
    PlatformModuleJNI.item_inventory_info_item_name_set(swigCPtr, this, value);
  }

  public String getItem_name() {
    return PlatformModuleJNI.item_inventory_info_item_name_get(swigCPtr, this);
  }

  public void setPrice(String value) {
    PlatformModuleJNI.item_inventory_info_price_set(swigCPtr, this, value);
  }

  public String getPrice() {
    return PlatformModuleJNI.item_inventory_info_price_get(swigCPtr, this);
  }

  public item_inventory_info() {
    this(PlatformModuleJNI.new_item_inventory_info(), true);
  }

}
