/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package platform;

public class platform_info {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected platform_info(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(platform_info obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PlatformModuleJNI.delete_platform_info(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUser_id(String value) {
    PlatformModuleJNI.platform_info_user_id_set(swigCPtr, this, value);
  }

  public String getUser_id() {
    return PlatformModuleJNI.platform_info_user_id_get(swigCPtr, this);
  }

  public void setPlatform_name(String value) {
    PlatformModuleJNI.platform_info_platform_name_set(swigCPtr, this, value);
  }

  public String getPlatform_name() {
    return PlatformModuleJNI.platform_info_platform_name_get(swigCPtr, this);
  }

  public void setDevice_name(String value) {
    PlatformModuleJNI.platform_info_device_name_set(swigCPtr, this, value);
  }

  public String getDevice_name() {
    return PlatformModuleJNI.platform_info_device_name_get(swigCPtr, this);
  }

  public void setManufacturer(String value) {
    PlatformModuleJNI.platform_info_manufacturer_set(swigCPtr, this, value);
  }

  public String getManufacturer() {
    return PlatformModuleJNI.platform_info_manufacturer_get(swigCPtr, this);
  }

  public void setOs_version(String value) {
    PlatformModuleJNI.platform_info_os_version_set(swigCPtr, this, value);
  }

  public String getOs_version() {
    return PlatformModuleJNI.platform_info_os_version_get(swigCPtr, this);
  }

  public void setDevice_language(String value) {
    PlatformModuleJNI.platform_info_device_language_set(swigCPtr, this, value);
  }

  public String getDevice_language() {
    return PlatformModuleJNI.platform_info_device_language_get(swigCPtr, this);
  }

  public platform_info() {
    this(PlatformModuleJNI.new_platform_info(), true);
  }

}
