/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package platform;

public class PlatformModuleJNI {
  public final static native long new_item_info_vector__SWIG_0();
  public final static native long new_item_info_vector__SWIG_1(long jarg1);
  public final static native long item_info_vector_size(long jarg1, item_info_vector jarg1_);
  public final static native long item_info_vector_capacity(long jarg1, item_info_vector jarg1_);
  public final static native void item_info_vector_reserve(long jarg1, item_info_vector jarg1_, long jarg2);
  public final static native boolean item_info_vector_isEmpty(long jarg1, item_info_vector jarg1_);
  public final static native void item_info_vector_clear(long jarg1, item_info_vector jarg1_);
  public final static native void item_info_vector_add(long jarg1, item_info_vector jarg1_, long jarg2, item_info jarg2_);
  public final static native long item_info_vector_get(long jarg1, item_info_vector jarg1_, int jarg2);
  public final static native void item_info_vector_set(long jarg1, item_info_vector jarg1_, int jarg2, long jarg3, item_info jarg3_);
  public final static native void delete_item_info_vector(long jarg1);
  public final static native long new_item_inventory_info_vector__SWIG_0();
  public final static native long new_item_inventory_info_vector__SWIG_1(long jarg1);
  public final static native long item_inventory_info_vector_size(long jarg1, item_inventory_info_vector jarg1_);
  public final static native long item_inventory_info_vector_capacity(long jarg1, item_inventory_info_vector jarg1_);
  public final static native void item_inventory_info_vector_reserve(long jarg1, item_inventory_info_vector jarg1_, long jarg2);
  public final static native boolean item_inventory_info_vector_isEmpty(long jarg1, item_inventory_info_vector jarg1_);
  public final static native void item_inventory_info_vector_clear(long jarg1, item_inventory_info_vector jarg1_);
  public final static native void item_inventory_info_vector_add(long jarg1, item_inventory_info_vector jarg1_, long jarg2, item_inventory_info jarg2_);
  public final static native long item_inventory_info_vector_get(long jarg1, item_inventory_info_vector jarg1_, int jarg2);
  public final static native void item_inventory_info_vector_set(long jarg1, item_inventory_info_vector jarg1_, int jarg2, long jarg3, item_inventory_info jarg3_);
  public final static native void delete_item_inventory_info_vector(long jarg1);
  public final static native void platform_info_user_id_set(long jarg1, platform_info jarg1_, String jarg2);
  public final static native String platform_info_user_id_get(long jarg1, platform_info jarg1_);
  public final static native void platform_info_platform_name_set(long jarg1, platform_info jarg1_, String jarg2);
  public final static native String platform_info_platform_name_get(long jarg1, platform_info jarg1_);
  public final static native void platform_info_device_name_set(long jarg1, platform_info jarg1_, String jarg2);
  public final static native String platform_info_device_name_get(long jarg1, platform_info jarg1_);
  public final static native void platform_info_manufacturer_set(long jarg1, platform_info jarg1_, String jarg2);
  public final static native String platform_info_manufacturer_get(long jarg1, platform_info jarg1_);
  public final static native void platform_info_os_version_set(long jarg1, platform_info jarg1_, String jarg2);
  public final static native String platform_info_os_version_get(long jarg1, platform_info jarg1_);
  public final static native void platform_info_device_language_set(long jarg1, platform_info jarg1_, String jarg2);
  public final static native String platform_info_device_language_get(long jarg1, platform_info jarg1_);
  public final static native long new_platform_info();
  public final static native void delete_platform_info(long jarg1);
  public final static native void item_info_item_name_set(long jarg1, item_info jarg1_, String jarg2);
  public final static native String item_info_item_name_get(long jarg1, item_info jarg1_);
  public final static native void item_info_consumable_set(long jarg1, item_info jarg1_, boolean jarg2);
  public final static native boolean item_info_consumable_get(long jarg1, item_info jarg1_);
  public final static native long new_item_info__SWIG_0();
  public final static native long new_item_info__SWIG_1(long jarg1, item_info jarg1_);
  public final static native void delete_item_info(long jarg1);
  public final static native void item_inventory_info_item_name_set(long jarg1, item_inventory_info jarg1_, String jarg2);
  public final static native String item_inventory_info_item_name_get(long jarg1, item_inventory_info jarg1_);
  public final static native void item_inventory_info_price_set(long jarg1, item_inventory_info jarg1_, String jarg2);
  public final static native String item_inventory_info_price_get(long jarg1, item_inventory_info jarg1_);
  public final static native long new_item_inventory_info();
  public final static native void delete_item_inventory_info(long jarg1);
  public final static native long new_Platform();
  public final static native void delete_Platform(long jarg1);
  public final static native long Platform_getPlatformInfo(long jarg1, Platform jarg1_);
  public final static native void Platform_showAd(long jarg1, Platform jarg1_);
  public final static native boolean Platform_isAdFree(long jarg1, Platform jarg1_);
  public final static native void Platform_purchaseAdFree(long jarg1, Platform jarg1_);
  public final static native void Platform_purchaseConsumable(long jarg1, Platform jarg1_, long jarg2, item_info jarg2_);
  public final static native void Platform_queryInventory(long jarg1, Platform jarg1_, long jarg2, item_info_vector jarg2_);
  public final static native void Platform_director_connect(Platform obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void Platform_change_ownership(Platform obj, long cptr, boolean take_or_release);
  public final static native void SetPlatform(long jarg1, Platform jarg1_);
  public final static native long GetPlatform();
  public final static native void SetAdRequestResult(boolean jarg1);
  public final static native void adFreePurchased();
  public final static native void consumablePurchased(long jarg1, item_info jarg1_);
  public final static native void reportInventory(long jarg1, item_inventory_info_vector jarg1_);

  public static long SwigDirector_Platform_getPlatformInfo(Platform jself) {
    return platform_info.getCPtr(jself.getPlatformInfo());
  }
  public static void SwigDirector_Platform_showAd(Platform jself) {
    jself.showAd();
  }
  public static boolean SwigDirector_Platform_isAdFree(Platform jself) {
    return jself.isAdFree();
  }
  public static void SwigDirector_Platform_purchaseAdFree(Platform jself) {
    jself.purchaseAdFree();
  }
  public static void SwigDirector_Platform_purchaseConsumable(Platform jself, long item) {
    jself.purchaseConsumable(new item_info(item, false));
  }
  public static void SwigDirector_Platform_queryInventory(Platform jself, long items) {
    jself.queryInventory(new item_info_vector(items, false));
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
