/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package platform;

public class Platform {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Platform(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Platform obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        PlatformModuleJNI.delete_Platform(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    PlatformModuleJNI.Platform_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    PlatformModuleJNI.Platform_change_ownership(this, swigCPtr, true);
  }

  public Platform() {
    this(PlatformModuleJNI.new_Platform(), true);
    PlatformModuleJNI.Platform_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

  public platform_info getPlatformInfo() {
    return new platform_info(PlatformModuleJNI.Platform_getPlatformInfo(swigCPtr, this), true);
  }

  public void showAd() {
    PlatformModuleJNI.Platform_showAd(swigCPtr, this);
  }

  public boolean isAdFree() {
    return PlatformModuleJNI.Platform_isAdFree(swigCPtr, this);
  }

  public void purchaseAdFree() {
    PlatformModuleJNI.Platform_purchaseAdFree(swigCPtr, this);
  }

  public void purchaseConsumable(item_info item) {
    PlatformModuleJNI.Platform_purchaseConsumable(swigCPtr, this, item_info.getCPtr(item), item);
  }

  public void queryInventory(item_info_vector items) {
    PlatformModuleJNI.Platform_queryInventory(swigCPtr, this, item_info_vector.getCPtr(items), items);
  }

}
