/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package platform;

public class PlatformModule {
  public static void SetPlatform(Platform arg0) {
    PlatformModuleJNI.SetPlatform(Platform.getCPtr(arg0), arg0);
  }

  public static Platform GetPlatform() {
    long cPtr = PlatformModuleJNI.GetPlatform();
    return (cPtr == 0) ? null : new Platform(cPtr, false);
  }

  public static void SetAdRequestResult(boolean shown) {
    PlatformModuleJNI.SetAdRequestResult(shown);
  }

  public static void adFreePurchased() {
    PlatformModuleJNI.adFreePurchased();
  }

  public static void consumablePurchased(item_info item) {
    PlatformModuleJNI.consumablePurchased(item_info.getCPtr(item), item);
  }

  public static void reportInventory(item_inventory_info_vector arg0) {
    PlatformModuleJNI.reportInventory(item_inventory_info_vector.getCPtr(arg0), arg0);
  }

}
