/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.8
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

#ifndef SWIG_PlatformModule_WRAP_H_
#define SWIG_PlatformModule_WRAP_H_

class SwigDirector_Platform : public Platform, public Swig::Director {

public:
    void swig_connect_director(JNIEnv *jenv, jobject jself, jclass jcls, bool swig_mem_own, bool weak_global);
    SwigDirector_Platform(JNIEnv *jenv);
    virtual ~SwigDirector_Platform();
    virtual platform_info getPlatformInfo();
    virtual void showAd();
    virtual bool isAdFree();
    virtual void purchaseAdFree();
    virtual void purchaseConsumable(item_info item);
    virtual void queryInventory(std::vector< item_info > items);
public:
    bool swig_overrides(int n) {
      return (n < 6 ? swig_override[n] : false);
    }
protected:
    Swig::BoolArray<6> swig_override;
};


#endif
